### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by davenquinn** [EarthCubeGeochron/Sparrow#17]
Sparrow's documentation is hosted at https://sparrow-data.org. It includes a main documentation website and several "demo" instances of the Sparrow application. The current instance of the documentation is out of date (last substantively improved in summer 2019). It must be modernized and improved; also, a streamlined process for updating must be created to enable ongoing updates.

### Envisioned structure

The documentation website needs to contain information about several parts of the project:

- Overall motivation, funding, and project design
- Example implementations
- Installation
- Code-level documentation
  - Backend (Python and PostgreSQL)
  - Frontend (Javascript, sometimes in Coffeescript or Typescript flavors)
- How to extend and write plugins
- Usage
  - Importing data
  - Interacting with the API
  - Upgrading, backing up
- News and updates

### New documentation needed

All parts of Sparrow need improvements to documentation, but several key areas are entirely missing:

- [ ] The plugin interface: new since ~December 2019 and mostly defined: this is the main extension point for lab developers, and lack of documentation blocks use, although instructive examples exist within the codebase.
- [ ] Similarly, the new schema-based import interface is defined and extensively tested (although not yet adapted to all situations) but has no instructions for use. As the preferred mechanism for inserting data into Sparrow in most circumstances, *the lack of this documentation is a critical blocker for independent use by labs.*
- [ ] Many presentations and posters by the Sparrow team.
- [ ] A blog to hold textual updates including workshop reports, submitted abstracts, announcements, etc.

### Technical improvements

In addition to needing new content, the documentation effort is held back by several technical challenges. Several parts of the documentation creation process are broken or unwieldy. These issues will make it difficult to add significantly to the documentation until they are resolved.

- [ ] Continuous integration is crucial for collaborative documentation management (see #16).
- [ ] [Sphinx](https://www.sphinx-doc.org/en/master/)-based documentation of the Python backend does not build correctly and is thus not included on the documentation website.
- [ ] The [Gatsby](https://www.gatsbyjs.org/) static site generator we are using for the main documentation page has a surprisingly high barrier to entry and requires knowledge of some esoteric technology (GraphQL) to productively use. Switching to a simpler and more documentation-focused site generator would probably be ideal. It looks like [Docusaurus](https://docusaurus.io/) is the best option — relative to other solutions, it maintains the chief advantage of Gatsby that it is based on React (also used for the Sparrow frontend). However, it seems easier to use all around.
- [ ] There is a lot of static content in the documentation repository, making it relatively weighty. Work is in progress to move some static assets (e.g. figures) to a S3 bucket. (Overall, the added weight of docs will matter less once #15 is resolved and labs don't have to download the entire repository for every Sparrow installation.)
- [ ] Design and presentation of the website should be streamlined. See #8 for example.
- [ ] A succinct summary should be added to the repository README
